on:
  schedule:
  - cron: 0 0 0 * * ?
name: daily Issue Closure
jobs:
  cycle-weekly-close:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: daily-issue-closure
      uses: bdougie/close-issues-based-on-label@master
      env:
        LABEL: custom
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
